# Generated by Django 5.0.7 on 2024-08-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_page_pic', models.ImageField(upload_to='static/blogs/images')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=180)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/blogs/images')),
            ],
            options={
                'verbose_name': 'وبلاگ',
                'verbose_name_plural': 'وبلاگ',
            },
        ),
    ]
