# Generated by Django 5.0.7 on 2024-08-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_product', models.CharField(max_length=150, verbose_name='اسم جنس')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='static/products/images', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'اجناس ویژه',
                'verbose_name_plural': 'اجناس ویژه',
            },
        ),
        migrations.CreateModel(
            name='NewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default=None, max_length=255, verbose_name='اسم جنس')),
                ('price', models.IntegerField(default=None, verbose_name='قیمت')),
                ('image', models.ImageField(upload_to='static/products/images', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'اجناس جدید',
                'verbose_name_plural': 'اجناس جدید',
            },
        ),
    ]
