# Generated by Django 5.0.7 on 2024-08-05 20:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproducts',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='products/images/'),
            preserve_default=False,
        ),
    ]
