# Generated by Django 5.0.7 on 2024-08-18 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproducts',
            name='description',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='توضیحات'),
            preserve_default=False,
        ),
    ]
