# Generated by Django 5.0.7 on 2024-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_newproducts_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelOfDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.CharField(max_length=350)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جنس روز',
                'verbose_name_plural': 'اجناس روز',
            },
        ),
    ]
