# Generated by Django 5.0.7 on 2024-08-18 11:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_modelofday'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelofday',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/products/images', verbose_name='تصویر جنس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='modelofday',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پست'),
        ),
        migrations.AlterField(
            model_name='modelofday',
            name='description',
            field=models.CharField(max_length=350, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='modelofday',
            name='name',
            field=models.CharField(max_length=155, verbose_name='اسم جنس'),
        ),
    ]
