# Generated by Django 5.0.7 on 2024-08-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_modelofday_image_alter_modelofday_date_posted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelofday',
            name='price',
            field=models.IntegerField(default=None, verbose_name='قیمت'),
        ),
    ]
